### ISSUE TITLE
Allow for multiple instances

### ISSUE THREAD

**Issue by RangerMauve** [ozantunca/DispatcherJS#1]
Hey this library looks pretty promising. Would it be possible to give the option of having multiple instance of the dispatcher? In my use case, there are several independent applications running concurrently and it'd be kind of bad if they mixed together.

**Comment by ozantunca** [comment]
Hey thanks for your interest. I thought that wouldn't be needed but if you say so I will be adding that feature too shortly.

**Comment by RangerMauve** [comment]
Thanks!

**Comment by ozantunca** [comment]
You can now have seperate instances of dispatcher by initializing it like this:

``` javascript
  var Dispatcher = require('dispatcherjs')
    , dispatcher = new Dispatcher()
    , dispatcher2 = new Dispatcher();
```

**Comment by RangerMauve** [comment]
Cool, thanks!
